// This registry is shared by the router, the capabilities page and generated docs.
// Reserved contracts are design proposals, not production API compatibility promises.
const route = (method, path, name, handler, request, response, rule) => ({ method, path, name, handler, implemented: true, request, response, rule });
export const routes = [
  route('GET', '/api/health', '服务状态', 'health', null, '{ mode: "demo", persistence: "json-file", today }', '只说明本地服务可响应，不代表生产健康探针或容灾可用。'),
  route('GET', '/api/actors', '演示身份列表', 'actors', null, 'Actor[]：id/name/role/department', '固定四个虚构角色。X-Demo-Actor 只用于流程演示，不能认证身份。'),
  route('GET', '/api/state', '演示页面快照', 'snapshot', null, '{ actors, devices, orders, plans, tasks, messages, audit, summary }', '全量读取演示数据；消息只返回当前角色的消息，审计仅管理员返回。设备和业务记录没有企业数据隔离。'),
  route('GET', '/api/summary', '基础统计', 'summary', null, '{ devices, openOrders, pendingReview, pendingTasks, overdueTasks, closedOrders, today }', '直接统计当前记录；超期指未完成任务的 scheduledDate 早于上海日期。不计算 MTBF/MTTR/OEE。'),
  route('GET', '/api/capabilities', '接口实现清单', 'capabilities', null, '{ implemented: Contract[], reserved: Contract[] }', '与路由使用同一注册表；每个预留接口都有输入示例、依赖和验收要求。'),
  route('GET', '/api/devices', '设备查询', 'devices', { query: '可选 q：按编码、名称、位置包含查询' }, 'Device[]（含 derivedStatus）', 'derivedStatus 由未关闭工单推导：reported/repairing/active；不代表实时采集到的物理运行状态。'),
  route('POST', '/api/devices', '新增设备', 'createDevice', { code: 'EQ-004', name: '演示设备', location: '一号车间', category: '加工设备' }, 'Device：id/code/name/location/category/status/version/createdAt', '仅管理员。code 1–40、name/location 1–80、category 1–40 字符；编码忽略大小写唯一。'),
  route('GET', '/api/devices/{id}/history', '设备履历', 'deviceHistory', null, '{ device, orders: Order[], tasks: Task[], events: AuditEvent[] }', '只查询该设备关联的工单、任务、计划事件；没有文档版本、调拨或报废履历。'),
  route('GET', '/api/orders', '维修工单列表', 'orders', { query: '可选 status：工单状态；可选 deviceId：设备 ID' }, 'Order[]', '状态合法值见状态机；列表无分页，仅适合少量演示数据。'),
  route('GET', '/api/orders/{id}', '工单详情', 'order', null, 'Order（含 completions/reviews/history）', 'id 不存在返回 404；所有完工和验收尝试保留。'),
  route('POST', '/api/orders', '报修', 'createOrder', { deviceId: '<设备 ID>', title: '运行异响', description: '演示故障描述', priority: 'normal' }, 'Order：初始 pending_assignment、version=1', '标题 1–100、描述 1–1000 字符；priority=normal/urgent；允许各演示角色报修。重复 POST 会创建新工单，生产请求幂等尚未实现。'),
  route('POST', '/api/orders/{id}/assign', '派单/接单前改派', 'assignOrder', { version: 1, assigneeId: 'technician' }, 'Order：pending_acceptance', '管理员；只允许 pending_assignment/pending_acceptance，目标须为维修人员。处理中转单另待实现。'),
  route('POST', '/api/orders/{id}/accept', '接单', 'acceptOrder', { version: 2 }, 'Order：in_progress', '仅被指派人或管理员；须为 pending_acceptance。'),
  route('POST', '/api/orders/{id}/reject', '拒单', 'rejectOrder', { version: 2, reason: '需要重新安排人员' }, 'Order：pending_assignment，清空 assigneeId', '仅被指派人或管理员；须为 pending_acceptance；原因 1–500 字符。'),
  route('POST', '/api/orders/{id}/complete', '提交完工', 'completeOrder', { version: 3, summary: '检查连接件并记录结果', workMinutes: 30, materials: '密封圈 1 个（仅文字记录）', safetyConfirmed: true }, 'Order：pending_review；新增 Completion', '仅执行人或管理员；须为 in_progress；summary 1–1000、materials 可选 0–500；工时 1–10080 整数分钟；安全勾选不等于安全证据。'),
  route('POST', '/api/orders/{id}/review', '验收/退回', 'reviewOrder', { version: 4, decision: 'accept', note: '演示验收通过' }, 'Order：accept→closed；return→in_progress', '管理员或原报修人；须为 pending_review；note 1–500；完工和退回记录均保留。未实现多人验收、签名和职责分离。'),
  route('POST', '/api/orders/{id}/cancel', '取消工单', 'cancelOrder', { version: 1, reason: '重复报修' }, 'Order：cancelled', '报修人仅能取消 pending_assignment；管理员还可取消 pending_acceptance/in_progress；待验收及终态不能取消。'),
  route('GET', '/api/plans', '维保计划列表', 'plans', null, 'Plan[]', '保存周期和检查项；暂停只影响之后的生成，不撤销既有任务。'),
  route('POST', '/api/plans', '新增周期计划', 'createPlan', { deviceId: '<设备 ID>', name: '每日点检', type: 'inspection', intervalDays: 1, nextDueDate: '2026-09-27', assigneeId: 'inspector', checklist: ['油位', '运行声音'] }, 'Plan：active=true、version=1', '仅管理员；type=inspection/maintenance；周期 1–3650 天；日期有效且为 2000–2100；检查项 1–20 个、各 1–100 字且不重复；执行人为 technician/inspector。'),
  route('PATCH', '/api/plans/{id}', '暂停/恢复计划', 'togglePlan', { version: 1, active: false }, 'Plan', '仅管理员；只更新 active；模板、周期、指派及日期变更尚未实现。'),
  route('POST', '/api/plans/generate', '生成到期任务', 'generateTasks', { throughDate: '2026-09-27' }, '{ generated: Task[], count, throughDate }', '仅管理员；截止日不得晚于上海今天；按计划原到期日逐周期补齐，每次最多 100 条；计划+日期去重；推进下次日期；无后台定时器。'),
  route('GET', '/api/tasks', '维保任务列表', 'tasks', { query: '可选 status：pending/completed' }, 'Task[]', '任务携带生成时检查项快照；同时列出保养和点检。'),
  route('GET', '/api/tasks/{id}', '任务详情', 'task', null, 'Task（含 checklist/results/history/linkedOrderId）', '只提供两态 pending/completed；未实现接单、复核或撤销。'),
  route('POST', '/api/tasks/{id}/complete', '执行维保/异常转维修', 'completeTask', { version: 1, results: [{ itemId: '<task.checklist 中的 ID>', verdict: 'abnormal', reading: '演示读数', remark: '演示异常：有异响' }], note: '作业备注' }, 'Task：completed；异常时 linkedOrderId 指向新 Order', '仅指派人或管理员；必须提交所有项目且不重复；verdict=normal/abnormal；异常 remark 必填；读数为文字，无阈值判定；所有异常汇总为一个工单，与任务同次原子保存。'),
  route('GET', '/api/messages', '站内消息', 'messages', null, 'Message[]', '仅当前演示角色的消息；非真实短信、微信或 APP 推送。'),
  route('PATCH', '/api/messages/{id}/read', '消息已读', 'readMessage', {}, 'Message：read=true', '只可修改自己的消息；重复标记已读无副作用，不使用 version。'),
  route('GET', '/api/audit', '演示业务事件', 'audit', null, 'AuditEvent[]', '仅管理员；记录业务动作而非所有读写、登录或修改前后镜像；未防篡改。'),
];

const future = (id, name, method, path, request, response, scope, dependencies, acceptance) => ({ id, name, method, path, request, response, scope, dependencies, acceptance, implemented: false, status: 'reserved' });
export const reserved = [
  future('AUTH', '真实账号与认证', 'POST', '/api/auth/login', { account: '<账号>', credential: '<密码或授权票据>', provider: 'password' }, '{ token, expiresAt, user }', '账号注册、密码找回、验证码、第三方登录、账号停用、实名认证、登录日志。', ['企业身份源及开放注册政策', '令牌与会话方案、密码和验证码策略'], ['错误凭据及过期会话被拒绝', '停用账号不能继续调用接口，登录行为可审计']),
  future('ACCESS', '组织与权限配置', 'PUT', '/api/access/roles/{id}', { version: 1, name: '<角色>', menus: [], operations: [], dataScope: { departmentIds: [] }, fields: [] }, '{ role, version }', '部门/班组维护、组织树、角色自定义、菜单/操作/字段/行级权限、角色复制及权限审计。', ['组织主数据及一人一责的授权规则', '真实认证和企业/外协数据边界'], ['扫码、导出、附件、分享都服从权限', '不同部门/企业/外协越权请求返回 403，变更可追溯']),
  future('SETTINGS', '业务参数与移动表单', 'PUT', '/api/settings', { version: 1, dictionaries: {}, messageTemplates: [], mobileForms: [] }, '{ settings, version }', '故障字典、周期规则、公告、移动字段及布局、消息偏好设置；配置升级与兼容。', ['参数归属、编辑权限及版本策略', '表单字段类型、校验及既有记录兼容规则'], ['配置修改不破坏历史记录', '非法字段/规则被拒绝，配置有版本和审批记录']),
  future('ASSET', '资产档案与生命周期', 'POST', '/api/devices/{id}/lifecycle', { version: 1, action: 'transfer', targetLocation: '<位置>', reason: '<原因>', attachments: [] }, '{ requestId, status, deviceVersion }', '设备编辑、Excel 导入导出、附件、标签打印、原值折旧、验收调拨借用封存报废。', ['资产数据与财务口径、审批人', '文件服务、标签规格、设备状态流转'], ['导入有错误行报告和回滚边界', '审批前后状态正确，履历保留前后值，报废设备不生成新任务']),
  future('COMPLIANCE', '特种设备与证书', 'POST', '/api/compliance/inspections', { deviceId: '<ID>', dueDate: '<日期>', certificateId: '<ID>', standardVersion: '<适用规则版本>' }, '{ inspectionId, reminders }', '检定校验、安全检查、人员资质与到期提醒。', ['业务及安全负责人确认适用规则', '合格机构、证书数据源、提前提醒规则'], ['适用期限及资质限制正确', '过期/不合格的处置流程和证据可追溯']),
  future('BOM', '设备关系与 BOM', 'PUT', '/api/devices/{id}/bom', { version: 1, children: [{ deviceId: '<ID>', quantity: 1 }], sparePartIds: [] }, '{ tree, version }', '整机部件零件、父子/替代关系、备件关联。', ['设备及备件编码体系', '版本、替代件及数量单位规则'], ['环路与重复关系被拒绝', '变更保留版本，领料可按适用 BOM 查件']),
  future('IOT', '设备数据与 IoT 告警', 'POST', '/api/iot/telemetry', { deviceId: '<ID>', timestamp: '<ISO 时间>', metrics: { temperature: 0 }, eventId: '<源唯一事件>' }, '{ accepted, duplicate, alarmIds }', 'MQTT/OPC UA/Modbus 等网关接入、运行状态、时序数据、异常阈值及自动报修。', ['网关及点位表、采样频率、单位', '时钟、断连、重复/乱序与设备映射规则'], ['重复与乱序数据处理可验证', '告警抑制/恢复准确，自动工单不重复，物理状态与业务状态区分']),
  future('SCHEDULE', '高级计划与排程', 'POST', '/api/scheduling/preview', { planIds: [], horizon: { from: '<日期>', to: '<日期>' }, triggers: ['runtime'], resourceIds: [] }, '{ proposedTasks, conflicts, explanation }', '自动定时生成、运行时长/产量/状态触发、甘特图、负载、批量调整和路线规划。', ['生产日历、运行/产量数据、人员技能', '计划变更、补任务、停用和调度规则'], ['跨时区/周期边界与重试不重复', '排程冲突可解释，暂停/变更对既有任务的影响明确']),
  future('WORKFLOW', '派单、SLA 与流程引擎', 'POST', '/api/workflows/definitions', { name: '<流程>', version: 1, nodes: [], rules: { assignment: 'skill', timeoutMinutes: 60 } }, '{ definitionId, version, validation }', '自动派单、抢单、处理中转单/挂起、多节点审批、委托、SLA 计时和超时升级。', ['技能及工作日历、流程节点权限', '计时暂停、升级责任人、流程版本与在途兼容规则'], ['并发抢单唯一成功，非法流转失败', '超时边界及审批委托可验证，流程修改不破坏在途单据']),
  future('COST', '费用、绩效及高级指标', 'POST', '/api/analytics/calculate', { period: { from: '<日期>', to: '<日期>' }, metrics: ['MTBF', 'MTTR', 'OEE'], dimensions: ['department'] }, '{ metrics, missingInputs, sourceReferences }', '人工耗材外协费用、停机时间、MTBF/MTTR/OEE、趋势/排名、满意度及绩效。', ['指标字典、生产时长/产量/良品及故障数据', '费率、成本归集、统计排除规则和验收人'], ['指标能逐项回查原始数据', '缺少运行/生产数据时明确不可计算，不返回伪造的零值']),
  future('KNOWLEDGE', '故障知识与智能检索', 'GET', '/api/knowledge/search', { query: { q: '<故障代码或关键词>', deviceModel: '<型号>' } }, '{ items, total, sourceReferences }', '故障分类、案例、FAQ、应急方案、故障树、帕累托及类似案例推荐。', ['审核后的知识来源、权限和内容责任人', '版本、适用设备型号、安全内容审核规则'], ['检索结果有来源及适用范围', '受限资料不可泄露；推荐错误或无证据时有明确处理路径']),
  future('INVENTORY', '备件、领退料与盘点', 'POST', '/api/inventory/transactions', { requestId: '<唯一请求>', kind: 'issue', warehouseId: '<ID>', orderId: '<ID>', lines: [{ partId: '<ID>', quantity: 1, unit: '<单位>' }] }, '{ transactionId, balances, ledgerReferences }', '备件分类、多仓库/库位、占用、领退料、以旧换新、盘点盘盈亏、库存预警。', ['仓库及备件主数据、单位和唯一入账凭据', '库存/工单耗材的扣减时点、并发锁及成本规则'], ['同一请求只入账一次，库存与流水可对账', '不足库存与并发领料正确处理，退料不重复增加库存']),
  future('PROCUREMENT', '采购及供应商合同', 'POST', '/api/procurement/requests', { supplierId: '<ID>', reason: '<原因>', lines: [{ partId: '<ID>', quantity: 1 }], contractId: '<ID>' }, '{ requestId, approvalStatus }', '采购申请审批、供应商合同、价格趋势、交货质量、急采及电子发票。', ['ERP/采购主责、供应商编码、合同规则', '税务发票接口、验收及结算责任人'], ['申请、收货、库存、结算可对账', '供应商仅能查看本方单据，重复同步不重复入账']),
  future('REPORT', '报表、打印和大屏', 'POST', '/api/reports/export', { reportType: '<类型>', filters: {}, format: 'pdf', templateId: '<ID>' }, '{ jobId, status, downloadUrl, expiresAt }', '标准报表、可视化图表、大屏、自定义报表、BI 钻取、定时生成、PDF/Excel/打印模板。', ['数据口径及字段权限', '文件生成器、模板、性能容量和下载有效期'], ['导出与页面查询口径一致且无越权字段', '大数据异步导出可取消，模板及打印结果人工验收']),
  future('INTEGRATION', 'ERP/OA/MES/HR 接口', 'POST', '/api/integrations/jobs', { system: 'ERP', direction: 'import', entity: 'equipment', cursor: '<游标>', requestId: '<唯一请求>' }, '{ jobId, accepted, reconciliationUrl }', '跨系统主数据、单据同步、接口配置及同步任务。', ['逐系统接口文档、沙箱、姓名及交付承诺', '数据主责、编码映射、游标、错误补偿规则'], ['失败重试及重复请求不重复建账', '双边可对账，失败记录可定位并按授权补偿']),
  future('OUTSOURCE', '委外与维保商协作', 'POST', '/api/outsource/orders', { orderId: '<ID>', supplierId: '<ID>', contractId: '<ID>', expectedReturnDate: '<日期>' }, '{ externalOrderId, status }', '取件维修送回、报价、外委费用、验收评分、合同和结算。', ['外协身份、数据隔离和服务合同', '内部与外部状态映射、付款与验收权责'], ['外协仅操作所属任务', '内外工单状态一致且报价、发票、验收记录可关联']),
  future('FILE', '照片、视频与技术资料', 'POST', '/api/files/uploads', { entityType: 'order', entityId: '<ID>', filename: '<名称>', contentType: 'image/jpeg', size: 1 }, '{ uploadId, uploadUrl, expiresAt }', '作业前后照片、视频、语音、图纸手册、标注、水印、上传及下载。', ['文件存储与访问鉴权、大小和类型限制', '保留期、扫描、失败重传及附件备份'], ['越权上传/下载失败', '伪造类型、大文件、重复与中断上传可验证，附件随数据恢复']),
  future('LABEL', '二维码/NFC/RFID 与分享', 'POST', '/api/labels/generate', { entityType: 'device', entityIds: [], format: 'qr', templateId: '<ID>' }, '{ labels, printJobId }', '唯一标签、打印样式、扫码身份跳转、NFC/RFID 及微信分享。', ['标签编码/打印机和端硬件能力', '链接有效期、登录跳转及共享权限'], ['标签可实物扫码并找到正确设备', '分享/标签不能绕过身份与数据权限，作废标签失效']),
  future('MOBILE', '微信/支付宝与原生 APP', 'POST', '/api/mobile/session', { platform: 'wechat', authorizationCode: '<授权码>', appVersion: '<版本>' }, '{ session, permittedFeatures, updatePolicy }', '真实小程序、原生 APP、专属工作台、快捷入口、版本更新、平板适配。', ['平台主体/账号/域名、真机和发布流程', '登录、通知权限、应用版本及兼容矩阵'], ['在批准的机型、系统、平台版本验收', '平台授权和深链打开正常，低版本及权限拒绝有处理路径']),
  future('OFFLINE', '离线同步', 'POST', '/api/offline/sync', { clientId: '<ID>', baseVersion: 1, operations: [{ operationId: '<唯一ID>', entityId: '<ID>', payload: {} }] }, '{ acknowledged, conflicts, serverVersion }', '离线任务包、加密存储、附件同步、重复/冲突和账号权限变化。当前用户确认在线作业，后续按必要性立项。', ['实体版本、操作幂等和冲突裁决规则', '端侧密钥、安全擦除及断网验收环境'], ['重连后数据与附件无重复和遗漏', '并发冲突、退出登录及撤权后离线数据处理可验证']),
  future('SOP', '标准化安全作业', 'POST', '/api/sop/executions', { taskId: '<ID>', templateVersion: '<版本>', steps: [{ stepId: '<ID>', checked: true, evidenceIds: [] }] }, '{ executionId, nextStep, status }', 'SOP 顺序、安全确认、断电挂牌、工具核对、润滑五定及强制拍照。', ['经业务及安全负责人批准的作业标准', '不可跳步策略、证据要求及异常处置'], ['未完成必需步骤不能完工', '标准版本与每步证据保留；软件记录的责任边界确认']),
  future('SIGN', '电子签名、签章与归档', 'POST', '/api/signatures', { entityType: 'order', entityId: '<ID>', version: 1, signerId: '<ID>', provider: '<提供方>', evidenceId: '<ID>' }, '{ signatureId, documentHash, archivedUrl }', '手写签名、双签、多节点验收、电子签章、公章 PDF 归档。', ['身份确认、签署权限和适用要求', '签章服务、原文摘要、存证与保留规则'], ['签署对应的单据版本可证明且不可被后改冒用', '签署拒绝、撤回、归档及权限有验收记录']),
  future('LOCATION', '定位、导航与轨迹', 'POST', '/api/location/checkins', { taskId: '<ID>', deviceId: '<ID>', position: { latitude: 0, longitude: 0 }, proof: '<扫码或NFC证据>' }, '{ checkinId, matched, accuracy }', 'GPS/NFC 打卡、GIS、蓝牙 Beacon、巡检路线、库位/楼层导航、人员轨迹。', ['地图/室内设施、定位精度和有效区域', '知情授权、查看权限、保留期及伪造检测'], ['定位拒绝及低精度有处理路径', '实地到位判断可验收，轨迹仅授权人员可见']),
  future('OCR', '仪表 OCR 与采集', 'POST', '/api/ocr/readings', { taskId: '<ID>', itemId: '<ID>', fileId: '<ID>', meterType: '<型号>' }, '{ value, unit, confidence, requiresConfirmation }', '仪表盘识别、人工复核、阈值标红和照片水印。', ['仪表类型、样本、阈值和允许误差', '识别服务及人工确认规则'], ['在批准样本上达到业务确定的误差范围', '低置信度转人工，原图与最终确认读数关联']),
  future('TOOL', '工具借还与校准', 'POST', '/api/tools/loans', { toolId: '<ID>', borrowerId: '<ID>', dueAt: '<时间>', taskId: '<ID>' }, '{ loanId, status, calibrationValid }', '工具柜、借还、超时提醒、个人工具箱和校准期限。', ['工具编码、保管人、柜体接口和证书', '借还授权、逾期及失效工具限制'], ['重复借出被拒绝，归还可核对', '过期校准工具不能按批准规则投入作业']),
  future('COLLAB', '通讯与专家协作', 'POST', '/api/collaboration/rooms', { orderId: '<ID>', participantIds: [], mode: 'video' }, '{ roomId, joinUrl, expiresAt }', '工单评论/@、临时讨论组、视频/语音对讲、屏幕标注、专家技能库和人员联系。', ['通讯提供方、企业目录及专家技能', '参与权限、网络能力、录制和保留政策'], ['非参与者不能加入或读记录', '网络中断可恢复，协作内容与工单关联']),
  future('AR3D', 'AR 与 3D 模型', 'GET', '/api/models/{id}', { query: { deviceId: '<ID>', variant: 'exploded' } }, '{ modelUrl, version, parts, instructions }', '设备爆炸图、AR 步骤叠加、AR 眼镜远程协作。', ['合法模型资产、设备部件映射及版本', '端渲染/AR 硬件、定位精度与现场验证'], ['模型与实物版本匹配', '目标机型可加载，步骤位置和部件标识经现场确认']),
  future('TRAINING', '培训、证书与个人绩效', 'POST', '/api/training/enrollments', { courseId: '<ID>', employeeId: '<ID>', certificationId: '<ID>' }, '{ enrollmentId, progress, qualificationStatus }', '维修视频学习、考试认证、技能矩阵、计件工资、奖惩、个人提升。', ['培训内容、考试题库、证书及 HR 主责', '薪酬/奖惩口径、可见范围与批准流程'], ['学习考试与有效资质关联', '工资和评价可核对原始规则，敏感信息严格限制访问']),
  future('AI', '预测维护、孪生与语音', 'POST', '/api/intelligence/jobs', { kind: 'prediction', deviceId: '<ID>', datasetVersion: '<版本>', modelVersion: '<版本>', inputs: {} }, '{ jobId, result, evidence, uncertainty }', '故障概率、预知维修、数字孪生温度/振动映射、维修模拟、语音指令及记录。', ['历史/实时数据和模型资产、业务效果基线', '专项验证、误报漏报、人工确认与回退策略'], ['输出附数据/模型来源及不确定性', '按批准指标验收，语音/AI 不能未经授权自动产生关键业务动作']),
  future('LOWCODE', '低代码与国际化', 'POST', '/api/customizations', { version: 1, forms: [], workflows: [], reports: [], locale: 'zh-CN' }, '{ customizationId, validation, publishedVersion }', '拖拽表单、流程/报表配置、多语言和发布回滚。', ['字段/流程元模型、权限、插件边界', '翻译、时区单位、配置迁移及兼容政策'], ['恶意配置和权限绕过被拒绝', '历史单据兼容，发布回滚和多语言格式可验证']),
  future('SECURITY', '生产安全与审计回溯', 'POST', '/api/security/audit-exports', { from: '<时间>', to: '<时间>', entityType: '<类型>', reason: '<原因>' }, '{ jobId, signedDigest, archiveUrl }', 'HTTPS、端存储加密、全量操作与前后值、版本回溯、防篡改及审计导出。', ['安全标准、密钥管理、保留期及审计权限', '日志链路与加密/解密恢复方案'], ['密钥轮换、越权和审计完整性可验证', '恢复/回溯保留历史且经过授权，不能通过改本地文件冒充历史']),
  future('BACKUP', '备份恢复与部署', 'POST', '/api/backups/jobs', { kind: 'backup', scope: 'database-and-files', restorePointId: null }, '{ jobId, status, manifest, verification }', '每日备份/保留30天、手动恢复、容灾、生产监控、多种云部署。', ['批准的恢复点/时间目标、存储及运行负责人', '数据库和附件一致备份、恢复权限及切换方案'], ['真实执行恢复演练并对账', '备份失败能告警，批准的恢复目标满足；导出 JSON 不算完整容灾']),
  future('PUSH', '多渠道消息与告警升级', 'POST', '/api/notifications/deliveries', { eventId: '<唯一事件>', recipientIds: [], channels: ['wechat'], templateId: '<ID>', variables: {} }, '{ deliveryId, channelResults, retryAt }', '微信/支付宝服务通知、短信、APP Push、偏好时段、多级提醒及库存/证书告警。', ['平台模板、许可、账号和渠道资费', '事件去重、重试、回执、静默时段及升级规则'], ['发送失败及限流可追踪并补发', '关键待办不依赖单次推送成功，不能承诺无遗漏触达']),
];

export function matchContract(method, pathname) {
  for (const contract of [...routes, ...reserved]) {
    if (contract.method !== method) continue;
    const pattern = new RegExp(`^${contract.path.replace(/\{id\}/g, '([^/]+)')}$`);
    const match = pathname.match(pattern);
    if (match) return { contract, id: match[1] ? decodeURIComponent(match[1]) : null };
  }
  return null;
}
